version: '3'
services:
  ubuntu-dev-base:
    image: yoshwata/ubuntu-dev-base:bionic
    command: /bin/bash
    volumes: &vol
      - ~:/work
      - ./.tmux.conf:/home/yoshwata/.tmux.conf
      - ./.bash_history:/home/yoshwata/.bash_history
      - ./.bash_profile:/home/yoshwata/.bash_profile
      - ./.path:/home/yoshwata/.path
      - ./.bash_prompt:/home/yoshwata/.bash_prompt
      - ./.exports:/home/yoshwata/.exports
      - ./.aliases:/home/yoshwata/.aliases
      - ./.functions:/home/yoshwata/.functions
      - ./.gitconfig.sh:/home/yoshwata/.gitconfig.sh
      # git ignored secret settings
      - ./.extra:/home/yoshwata/.extra
      - ./.kube:/home/yoshwata/.kube
    working_dir: /work
  power-tmux:
    image: yoshwata/power-tmux:bionic
    command: tmux new
    volumes: *vol
    working_dir: /work
  nvim:
    image: yoshwata/nvim:bionic
    command: tmux new
    volumes: *vol
    working_dir: /work
  nodejs:
    image: yoshwata/nodejs-dev-10:bionic
    command: tmux new
    volumes: *vol
    working_dir: /work
